### ISSUE TITLE
Login Credentials Invalid

### ISSUE THREAD

**Issue by minkuan88** [sngguojie/CZ3003-CMS#10]
Login with userhq, userpr, usercc all responded with a Login credentials invalid

**Comment by melvynsngg** [comment]
Sorry about that, I migrated locally but not on heroku. I just migrated on heroku and tested. It should work now

Example: /login/
request:
{
    "username" : "userhq",
    "password": "passwordhq"
}
response:
{
  "success": true,
  "id": 3,
  "groups": "HQ_Commander"
}
