### ISSUE TITLE
Merge Postman tests into one file

### ISSUE THREAD

**Issue by chinjieh** [sngguojie/CZ3003-CMS#12]
Currently Postman tests are distributed over numerous files. It would be good to have all tests in the same file (and hence **one** collection. Can still be separated as 'folders' within Postman).

Reason is to force running of all the tests at the same time. When it is in different files, some tests are missed out as separate collections have to be run independently.

**Comment by melvynsngg** [comment]
KIV until currently ongoing work is complete to avoid conflicts

**Comment by chinjieh** [comment]
Closed!
