### ISSUE TITLE
Frontend changed to use the new urls for incident logs

### ISSUE THREAD

**Issue by minkuan88** [sngguojie/CZ3003-CMS#27]
Changed to used these urls instead
/Incident/{incident_id}/logs/list/
/Incident/{incident_id}/logs/create/

no longer using the old urls
/main/list_logs/{incident_id}
/IncidentLog/create/

**Comment by chinjieh** [comment]
Alright, will close this when I remove the leftovers

**Comment by chinjieh** [comment]
Old urls have been removed!
