### ISSUE TITLE
Postman test for SMS fails

### ISSUE THREAD

**Issue by melvynsngg** [sngguojie/CZ3003-CMS#38]
After merging PR #37 , the postman test for SMS will fail.

**Comment by chinjieh** [comment]
Apparently this is intended...agree that all tests should pass though. Maybe mock or something to remove the failure

**Comment by melvynsngg** [comment]
@jiaqi1993 Can close this issue?

**Comment by jiaqi1993** [comment]
Issue resolved after passing incorrect credentials. Close.
