### ISSUE TITLE
Create Call Report

### ISSUE THREAD

**Issue by minkuan88** [sngguojie/CZ3003-CMS#40]
Request URL:https://crisismanagement.herokuapp.com/Incident/41/callreports/create/
Request Method:POST
Status Code:400 Bad Request
Form Data: {"caller_name":"Andy","contact_no":"87654321","description":"Flooding","dateTime":"2016-11-03T04:17:53.504Z"}

Response: Failed to save model Flooding: column IncidentCallReport_incidentcallreport.id does not exist
LINE 1: ...4:17:53.504000+00:00'::timestamptz, 41) RETURNING "IncidentC...
                                                                                                    ^

**Comment by chinjieh** [comment]
Should be fixed now. I had to rebuild the whole IncidentCallReport table, however...
@minkuan88 please update

**Comment by minkuan88** [comment]
tried, working now. able to create call report. thanks
