### ISSUE TITLE
Incident Update radius requires location

### ISSUE THREAD

**Issue by minkuan88** [sngguojie/CZ3003-CMS#43]
Making an update to incident's radius requires coord_lat and coord_long
possible to update just radius and not it's coordinates?

**Comment by chinjieh** [comment]
Uhh right now no, its not possible. Is there a workaround to retrieve and then use the existing coords instead?

**Comment by minkuan88** [comment]
will work around it then.

**Comment by chinjieh** [comment]
Ok closing this then
